runtime: php55

handlers:
- url: /style
  static_dir: asset/style

- url: /image/(.*\.(gif|png|jpg))
  static_files: asset/image/\1
  upload: image/(.*\.(gif|png|jpg))

- url: /.*
  script: index.php